language: go
go:
- master

env:
  global:
      - CGO_ENABLED=0
      - CC_TEST_REPORTER_ID=1d8ecc28ac0c41cf1898b38182b5fab36da2206136a6dac5d40098d920518b82

addons:
  artifacts: true
sudo: false
services:
 - docker

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - go get github.com/axw/gocov/gocov

script:
 - bin/test.sh
 - go build

after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t gocov

after_success:
  - bin/docker_push.sh
