apiVersion: v1
kind: ConfigMap
metadata:
  name: gpp-config
  labels:
    name: gpp-config
data:
  SSH_USER:
  SSH_ENDPOINT:
  GPP_USER:
  GPP_ENDPOINT:
  SELENIUM_SERVER: http://selenium.card-devops/wd/hub
  HAL_ENDPOINT: http://hal/alert/image
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gpp-monitor
  name: gpp-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpp-monitor
  template:
    metadata:
      labels:
        app: gpp-monitor
    spec:
      containers:
      - image: zamedic/gpp-monitor:1.45.1
        name: gpp-monitor
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: gpp-config
        - secretRef:
            name: gpp-secrets
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Africa/Johannesburg
---
kind: Service
apiVersion: v1
metadata:
  name: gpp-monitor
spec:
  selector:
    app: gpp-monitor
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8080
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: gpp-monitor
  annotations:
   kubernetes.io/ingress.class: istio
spec:
   rules:
     - host: <<Enter Host>>
       http:
         paths:
           - backend:
               serviceName: gpp-monitor
               servicePort: http

